# Generated by Django 4.1.1 on 2022-11-22 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarProduct',
            new_name='CartProduct',
        ),
    ]
