# Generated by Django 4.1.1 on 2022-11-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0002_rename_carproduct_cartproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='rate',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
