# Generated by Django 4.1.1 on 2022-11-26 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0004_rename_shipping_adress_order_shipping_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='discoubnt',
            new_name='discount',
        ),
    ]
